### PR TITLE
Add outside .container backgrounds

### PR DESCRIPTION
**Pull request by varffs**
- header
- pagination

### CODE REVIEW

**Comment by mikeyrayvon** [comment]
i think the entire pagination element should be clickable

**Comment by varffs** [comment]
Sure would be better than just the text. However does the :after element click too?

**Comment by mikeyrayvon** [comment]
unfortunately, no.  but i can fix it with some css so the whole thing clicks

**Comment by varffs** [comment]
seeing that this PR isnt actually about the pagination per se. I think close this and create an issue about click area. Then you do that issue branch if you want

**Comment by mikeyrayvon** [comment]
kk

**Pull request merged**
